name: Build Multi-Platform Releases

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller tkinterdnd2
    
    - name: Build Windows executable
      run: |
        pyinstaller main.py --name="TraducteurRenPyPro" --onefile --windowed --noconfirm --clean --hidden-import=tkinterdnd2 --hidden-import=utils.constants --hidden-import=utils.config --hidden-import=utils.logging --hidden-import=core.extraction --hidden-import=core.reconstruction --hidden-import=core.validation --hidden-import=core.file_manager --hidden-import=core.coherence_checker --hidden-import=ui.backup_manager --hidden-import=ui.interface --hidden-import=ui.tutorial --add-data="utils;utils" --add-data="core;core" --add-data="ui;ui"
    
    - name: Create Windows archive
      run: |
        cd dist
        Compress-Archive -Path TraducteurRenPyPro.exe -DestinationPath TraducteurRenPyPro-Windows-x64.zip
        Get-FileHash TraducteurRenPyPro.exe -Algorithm SHA256 | Out-File TraducteurRenPyPro-Windows.sha256
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TraducteurRenPyPro-Windows
        path: |
          dist/TraducteurRenPyPro-Windows-x64.zip
          dist/TraducteurRenPyPro-Windows.sha256
    
    - name: Release Windows
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/TraducteurRenPyPro-Windows-x64.zip
          dist/TraducteurRenPyPro-Windows.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller tkinterdnd2
    
    - name: Build Linux executable
      run: |
        pyinstaller main.py --name="TraducteurRenPyPro" --onefile --windowed --noconfirm --clean --hidden-import=tkinterdnd2 --hidden-import=utils.constants --hidden-import=utils.config --hidden-import=utils.logging --hidden-import=core.extraction --hidden-import=core.reconstruction --hidden-import=core.validation --hidden-import=core.file_manager --hidden-import=core.coherence_checker --hidden-import=ui.backup_manager --hidden-import=ui.interface --hidden-import=ui.tutorial --add-data="utils:utils" --add-data="core:core" --add-data="ui:ui"
    
    - name: Create Linux archive
      run: |
        cd dist
        tar -czf TraducteurRenPyPro-Linux-x64.tar.gz TraducteurRenPyPro
        sha256sum TraducteurRenPyPro > TraducteurRenPyPro-Linux.sha256
    
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TraducteurRenPyPro-Linux
        path: |
          dist/TraducteurRenPyPro-Linux-x64.tar.gz
          dist/TraducteurRenPyPro-Linux.sha256
    
    - name: Release Linux
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/TraducteurRenPyPro-Linux-x64.tar.gz
          dist/TraducteurRenPyPro-Linux.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}