# .github/workflows/build-releases.yml
name: Build & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

env:
  RELEASE_NAME: ${{ github.ref_name }}

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tkinterdnd2
          pip install pyinstaller
          # pip install -r requirements.txt

      - name: Build Windows Executable
        run: |
          echo "Construction du RenExtract pour Windows..."
          mkdir artifacts
          mkdir artifacts/windows
          pyinstaller --onefile --windowed --name "RenExtract" main.py
          copy "dist/RenExtract.exe" "artifacts/windows/"
          Compress-Archive -Path "artifacts/windows/RenExtract.exe" -DestinationPath "artifacts/windows/RenExtract-${{ env.RELEASE_NAME }}-Windows.zip"
        shell: pwsh

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ env.RELEASE_NAME }}
          path: artifacts/windows/*.zip

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk python3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tkinterdnd2
          pip install pyinstaller
          # pip install -r requirements.txt

      - name: Build Linux Binary
        run: |
          echo "Construction du RenExtract pour Linux..."
          mkdir -p artifacts/linux
          pyinstaller --onefile --name "RenExtract" main.py
          cp dist/RenExtract artifacts/linux/
          chmod +x artifacts/linux/RenExtract
          tar -czf artifacts/linux/RenExtract-${{ env.RELEASE_NAME }}-Linux.tar.gz -C artifacts/linux RenExtract

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ env.RELEASE_NAME }}
          path: artifacts/linux/*.tar.gz

  create-release:
    name: Create GitHub Release
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-${{ env.RELEASE_NAME }}
          path: release/windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-${{ env.RELEASE_NAME }}
          path: release/linux

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            release/windows/*.zip
            release/linux/*.tar.gz
          body: |
            ## 🎮 RenExtract ${{ github.ref_name }}
            
            **Outil de traduction avancé pour les scripts Ren'Py**
            
            ### 📥 Téléchargements
            - **Windows** : `RenExtract-${{ env.RELEASE_NAME }}-Windows.zip`
            - **Linux** : `RenExtract-${{ env.RELEASE_NAME }}-Linux.tar.gz`
            
            ### 🚀 Installation
            
            **Windows :**
            1. Téléchargez le fichier `.zip`
            2. Extraire l'archive
            3. Exécutez `RenExtract.exe`
            
            **Linux :**
            1. Téléchargez le fichier `.tar.gz`
            2. Extraire : `tar -xzf RenExtract-${{ env.RELEASE_NAME }}-Linux.tar.gz`
            3. Exécutez : `./RenExtract`
            
            ### ✨ Fonctionnalités principales
            - 📚 Système de glossaire permanent
            - ⚡ Extraction intelligente avec protection des codes
            - 🔧 Reconstruction précise
            - 🎯 Support Drag & Drop et Ctrl+V
            - ✅ Validation automatique des traductions
            - 🛡️ Sauvegardes automatiques de sécurité
            - 🌙 Interface moderne avec thèmes
            
            ### 🆕 Nouveautés ${{ env.RELEASE_NAME }}
            - Architecture refactorisée avec modules enhanced
            - Structure organisée par jeu : `temporaires/[NomDuJeu]/`
            - Glossaire permanent pour termes récurrents
            - Validation avancée avec rapports détaillés
            - Interface améliorée et thèmes vraiment différents
            
            ### 💡 Utilisation
            1. Générez vos fichiers de traduction avec le SDK Ren'Py
            2. Chargez le fichier `.rpy` dans l'outil
            3. Cliquez sur "⚡ Extraire" pour créer les fichiers à traduire
            4. Traduisez les fichiers `.txt` générés
            5. Cliquez sur "🔧 Reconstruire" pour créer le fichier traduit
            
            ---
            
            🎓 **Guide complet** disponible dans l'application via le bouton "🎓 Aide"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}